In [2]:
import numpy as np

# Create a simple array from 1 to 9
arr = np.arange(1, 10)
print("Array from 1 to 9:", arr)

# Create a 3x3 array with random integers between 1 and 9
arr = np.random.randint(1, 10, size=(3, 3))
print("Random 3x3 Array:\n", arr)


Array from 1 to 9: [1 2 3 4 5 6 7 8 9]
Random 3x3 Array:
 [[1 6 2]
 [5 3 2]
 [8 1 7]]


In [3]:
# Reset array with specific values and reshape it as 3x3 with random integers for demonstration
arr = np.random.randint(1, 10, size=(3, 3))

# Calculate and display sum, mean, and standard deviation
sum_num = np.sum(arr)
mean = np.mean(arr)
std_dev = np.std(arr)

print("Sum:", sum_num)
print("Mean:", mean)
print("Standard Deviation:", std_dev)

# Access and print a specific element
element = arr[1, 2]
print("Specific Element at [1,2]:", element)


Sum: 55
Mean: 6.111111111111111
Standard Deviation: 2.3778816176702997
Specific Element at [1,2]: 9


In [4]:
# Define two arrays
arr = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
arr_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Perform element-wise operations
add = arr + arr_1
multy = arr * arr_1
divide = arr / arr_1
sub = arr_1 - arr

print("\nAddition:\n", add)
print("Multiplication:\n", multy)
print("Division:\n", divide)
print("Subtraction:\n", sub)



Addition:
 [11 11 11 11 11 11 11 11 11 11]
Multiplication:
 [10 18 24 28 30 30 28 24 18 10]
Division:
 [10.          4.5         2.66666667  1.75        1.2         0.83333333
  0.57142857  0.375       0.22222222  0.1       ]
Subtraction:
 [-9 -7 -5 -3 -1  1  3  5  7  9]


In [5]:
# Generate a new 4x4 array with random integers between 1 and 9
arr = np.random.randint(1, 10, size=(4, 4))
print("Random 4x4 Array:\n", arr)

# Slice the array to get the first 2 rows and first 3 columns
element = arr[:2, :3]
print("Sliced Array (first 2 rows and 3 columns):\n", element)


Random 4x4 Array:
 [[5 9 1 4]
 [1 1 6 3]
 [7 5 4 6]
 [3 6 2 6]]
Sliced Array (first 2 rows and 3 columns):
 [[5 9 1]
 [1 1 6]]


In [6]:
# Create a 1D array with random integers between 1 and 100
arr = np.random.randint(1, 100, size=20)
print("Random Array of 20 Elements:\n", arr)

# Count elements greater than or equal to 25
count = np.sum(arr >= 25)
print("Count of Elements >= 25:", count)


Random Array of 20 Elements:
 [25  8 88 77 73 31 88 42 97 15 93 67  2 93 32 76 79 58 69  4]
Count of Elements >= 25: 16


In [7]:
# Create a 3x4 array with random integers between 1 and 100
arr = np.random.randint(1, 100, size=(3, 4))

# Calculate row and column sums
value_1 = np.sum(arr)  # Total sum of the array
value_2 = np.sum(arr, axis=1)  # Row-wise sum

print("3x4 Array:\n", arr)
print("Total Sum of Array:", value_1)
print("Row-Wise Sum:", value_2)


3x4 Array:
 [[64 59 24 42]
 [36 10 11 64]
 [67 96 13 52]]
Total Sum of Array: 538
Row-Wise Sum: [189 121 228]


In [8]:
# Find minimum and maximum values
min_num = np.min(arr)
max_num = np.max(arr)

print("Minimum Value:", min_num)
print("Maximum Value:", max_num)


Minimum Value: 10
Maximum Value: 96


In [9]:
# Create an array of 12 elements and reshape it into 3x4
arr = np.arange(12).reshape(3, 4)
print("Reshaped 3x4 Array:\n", arr)

# Flatten the array back to 1D
arr = arr.reshape(-1)
print("Flattened Array:", arr)


Reshaped 3x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [10]:
# Generate two sets of random values
x1 = np.random.normal(loc=0, scale=1, size=100)   # Normal distribution
x2 = np.random.uniform(low=0, high=1, size=100)   # Uniform distribution

# Calculate correlation coefficient
correlation_matrix = np.corrcoef(x1, x2)
correlation_coefficient = correlation_matrix[0, 1]

# Stack x1 and x2 into a dataset
dataset = np.column_stack((x1, x2))
elements = dataset[:5]

print("First 5 elements of Dataset:\n", elements)
print("Correlation Coefficient between x1 and x2:", correlation_coefficient)


First 5 elements of Dataset:
 [[-0.57941716  0.42248852]
 [ 1.61829726  0.68614064]
 [-0.80930283  0.83391282]
 [-1.7292749   0.40656526]
 [-0.06114398  0.77846381]]
Correlation Coefficient between x1 and x2: -0.10230631887137907


In [11]:
# Generate a 10x2 array of random integers between 0 and 50
arr_02 = np.random.randint(0, 50, size=(10, 2))

# Save array to CSV
np.savetxt("arr_02.csv", arr_02, delimiter=',', header='x1,x2', comments='')

# Load the CSV back into an array
loaded_arr = np.loadtxt('arr_02.csv', delimiter=',', skiprows=1)
print("Loaded Array from CSV:\n", loaded_arr)


Loaded Array from CSV:
 [[47.  0.]
 [37. 41.]
 [36. 20.]
 [24. 12.]
 [44. 14.]
 [41. 35.]
 [42. 18.]
 [13. 37.]
 [15. 42.]
 [22. 36.]]
